/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amos_file_manager_File */

#ifndef _Included_com_amos_file_manager_File
#define _Included_com_amos_file_manager_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amos_file_manager_File
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amos_file_manager_File_delete0
  (JNIEnv *, jobject,jstring);

/*
 * Class:     com_amos_file_manager_File
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_amos_file_manager_File_write0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_amos_file_manager_File
 * Method:    creat0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_amos_file_manager_File_creat0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_amos_file_manager_File
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amos_file_manager_File_close0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
